version: '3.8'

services:
  monitor:
    image: mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
    command: ["/bin/bash", "-c", "apt update && apt install iputils-ping -y && dotnet run --project DataConnectionMonitor/DataConnectionMonitor.csproj"]
    volumes:
      - .:/DataConnectionMonitor
      - ./output:/DataConnectionMonitor/output
    working_dir: /DataConnectionMonitor
    ports:
      - 5000:5000
      - 5001:5001

volumes:
  output: