version: '3.8'

services:
  monitor:
    image: mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
    command: ["/bin/bash", "-c", "apt update && apt install iputils-ping -y && dotnet run --project DataConnectionMonitor.csproj"]
    working_dir: /app
    volumes:
      - ./DataConnectionMonitor:/app
      - ./output:/app/output
    restart: unless-stopped
  api:
    image: mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
    command: ["/bin/bash", "-c", "dotnet run --project DataConnectionMonitorAPI.csproj"]
    working_dir: /app
    volumes:
      - ./DataConnectionMonitorAPI:/app
      - ./output:/app/data
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - FAILURES_DATA=data/connectionFailures.csv
volumes:
  output: