version: '3.8'

services:
  monitor:
    build: ./DataConnectionMonitor
    image: data-connection-monitor
    working_dir: /app
    volumes:
      - ./output:/app/output
    restart: unless-stopped
  api:
    image: mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
    command: ["/bin/bash", "-c", "dotnet run --project DataConnectionMonitorAPI.csproj"]
    working_dir: /app
    volumes:
      - ./DataConnectionMonitorAPI:/app
      - ./output:/app/data
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - DisconnectionsFile=data/connectionFailures.csv
      - LastSuccessfulConnectionFile=data/lastSuccessfulConnection.txt
      - CurrentStatusFile=data/currentStatus.txt
      - Port=5000
    depends_on:
      - monitor
  ui:
    build: ./DataConnectionMonitorUI
    image: data-connection-monitor-ui
    ports:
      - 80:8080
    environment:
      - UI_PORT=8080
      - API_PORT=5000
    depends_on:
      - api
volumes:
  output: